# Numpy
### Если задания покажутся сложными, рекомендую пройти краткий курс по основам numpy [ссылка1](https://stepik.org/lesson/241329/step/1?unit=213910), [ссылка2](https://stepik.org/lesson/16462/step/1?unit=4283)

In [2]:
import numpy as np
import random
import scipy.stats as sps
import cv2


### Задание 1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [3]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))
# выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?
# ========
print("ранг a =",a.ndim, "\nранг b =", b.ndim)
print("размер матрицы a =",a.shape,"\nразмер матрицы b =",b.shape)
# ========
print(a)
print(b)

ранг a = 2 
ранг b = 2
размер матрицы a = (100, 100) 
размер матрицы b = (100, 100)
[[0.24774186 0.1265713  0.79278914 ... 0.61507608 0.32925158 0.23860233]
 [0.16237597 0.40468878 0.05622366 ... 0.98163735 0.48606256 0.47076415]
 [0.40125163 0.97429949 0.1979786  ... 0.58832238 0.41994566 0.26212653]
 ...
 [0.74498713 0.06852691 0.84112926 ... 0.37043582 0.96899369 0.2258682 ]
 [0.12275312 0.68912567 0.49189205 ... 0.59572391 0.17861052 0.41978414]
 [0.18849541 0.91248462 0.36074947 ... 0.83518507 0.66225386 0.07736796]]
[[0.47466614 0.6603653  0.74035889 ... 0.64441612 0.24538678 0.02668445]
 [0.18233474 0.38488242 0.30368784 ... 0.28047206 0.09987077 0.5675729 ]
 [0.18490742 0.62844854 0.47322879 ... 0.22327153 0.28915253 0.06836587]
 ...
 [0.36289252 0.54108178 0.02611089 ... 0.19785372 0.83382869 0.49359007]
 [0.82929863 0.09873956 0.97067324 ... 0.11500596 0.9455408  0.74375016]
 [0.37496511 0.97652954 0.88420382 ... 0.75942508 0.39437466 0.64920444]]


Без использования numpy

In [43]:
def mult(a, b):
    x = len(a)
    result = None
    if len(a) != len(b):
      raise ValueError
    result = [[0 for j in range(x)] for i in range(x)]
    for i in range(x):
      for j in range(x):
        for k in range(x):
          result[i][j] += a[i][k] * b[k][j]
    # print("Размерность матрицы:", result.ndim) # 'list' object has no attribute 'shape'
    # print("Размер матрицы:", result.shape)
    return result

C использованием numpy

In [42]:
def np_mult(a, b):
    if len(a) != len(b):
      raise ValueError
    result = np.dot(a, b)
    print("Размерность матрицы:", result.ndim)
    print("Размер матрицы:", result.shape)
    return result

In [45]:
%%time
# засечем время работы функции без NumPy
M1 = mult(a, b)


CPU times: user 1.39 s, sys: 0 ns, total: 1.39 s
Wall time: 1.93 s


In [47]:
%%time
# засечем время работы функции с NumPy
M2 = np_mult(a, b)

Размерность матрицы: 2
Размер матрицы: (100, 100)
CPU times: user 1.33 ms, sys: 2.08 ms, total: 3.4 ms
Wall time: 3.33 ms


In [48]:
# проверим корректность
np.abs(np.array(M1) - M2).sum()

1.5120349416974932e-11

### Задание 2

Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве. Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без. Засеките время работы, как это показано в заданиях выше.

In [106]:
# пришлось изменить 3 на 10000, так функции без numpy справлялись быстрее
a = np.random.sample((1, 10000))
a = list(a)[0]
b = np.random.sample((1, 10000))
b = list(b)[0]
print(a, b)

[0.74003202 0.45017767 0.21059906 ... 0.73334974 0.83282376 0.8180769 ] [0.51840171 0.97670793 0.02060841 ... 0.962641   0.2761077  0.07026514]


In [107]:
def scalar_product(a,b):
    s = 0
    for i in range(len(a)):
      s += a[i] * b[i]
    return s

In [108]:
def np_scalar_product(a,b):
    s = np.dot(a, b)
    return s

In [110]:
%time product_1 = scalar_product(a,b)
%time product_2 = np_scalar_product(a,b)
# проверим корректность:
np.abs(product_1 - product_2).sum()

CPU times: user 4.76 ms, sys: 58 µs, total: 4.82 ms
Wall time: 4.79 ms
CPU times: user 81 µs, sys: 0 ns, total: 81 µs
Wall time: 86.5 µs


5.9117155615240335e-12

Почему методы ***numpy*** оказываются эффективнее? Что вы можете сказать о скорости вычислений в NumPy?

**Ответ:** Библиотека numpy написана на C, поэтому работает эффективнее кода на python. На больших вычислениях скорость numpy будет превосходить решения на python в несколько раз.

------------------

### Задание 3
Напишите функцию, которая находим сумму четных диагональныех элементов квадратной матрицы. Если таких элементов нет, то вывести `0`.

In [111]:
# функция, решающая задачу с помощью NumPy
def np_diag_2k(a):
  res = np.array(a)
  x = res.shape[0]
  res = np.sum(res.diagonal()[res.diagonal() % 2 == 0])
  return res

In [112]:
# зададим некоторую квадратную матрицу
a = np.random.randint(1, 10, size=(5, 5))
a

array([[5, 3, 1, 1, 7],
       [2, 5, 1, 5, 7],
       [7, 4, 4, 8, 4],
       [7, 1, 1, 2, 3],
       [9, 2, 3, 1, 9]])

In [117]:
%%time
# засечем время работы функции с NumPy
np_diag_2k(a)

CPU times: user 199 µs, sys: 1.01 ms, total: 1.2 ms
Wall time: 1.18 ms


6

### Задание 4
На вход дан двумерный массив $X$. Напишите функцию, которая для каждой строчки $x = (x_1, x_2, \ldots, x_n)$ массива $X$  строит строчку $s = (s_1, s_2, \ldots, s_n)$, где $s_k=\frac{x_1+...+x_k}{k}$, а затем выдаёт массив из построенных строчек. Используйте библиотеку numpy (вам поможет функция cumsum). Выходом функции должен быть двумерный массив той же формы, что и $X$.

In [138]:
# функция, решающая задачу с помощью NumPy
def np_sec_av(*A):
    x = np.array(A)
    result = np.cumsum(x) / np.arange(1, x.shape[1]+1)
    return result

In [139]:
# зададим некоторую последовательность и проверим ее на ваших функциях.
# функция должна работать ~ в 50 раз быстрее, чем без Numpy
A = sps.uniform.rvs(size=10**3)
print(A)

%time S2 = np_sec_av(A)

[6.44796186e-01 6.23838092e-01 6.79487716e-01 1.15799595e-01
 7.95923780e-01 3.24982326e-01 2.97676831e-01 5.02978299e-01
 7.33324292e-01 8.53797105e-01 4.78429378e-01 2.46774842e-02
 2.41240996e-01 4.30720365e-01 2.42714216e-01 7.87359022e-02
 2.87935802e-01 7.62925034e-01 5.12297423e-01 6.58221012e-01
 8.90848812e-01 5.24701308e-01 6.31242943e-01 3.56357005e-01
 3.84170111e-01 9.81775265e-01 9.67001777e-01 7.90866638e-01
 2.26641552e-01 8.63154380e-01 8.67946982e-01 5.92048863e-01
 5.46711630e-01 1.39381240e-01 5.91212546e-01 6.10903080e-01
 4.99636188e-01 5.25747622e-01 4.22960116e-01 6.04351660e-01
 7.64607063e-01 9.52610955e-01 2.85511337e-01 6.80253828e-01
 5.72313688e-01 3.42051417e-01 9.48507575e-01 4.54113551e-01
 2.71159655e-01 7.02465218e-01 1.62808688e-01 7.40115370e-01
 9.79719491e-02 8.04639623e-01 7.22654865e-01 1.39135900e-01
 3.76001078e-01 6.19757718e-01 5.18643972e-01 2.35053538e-01
 9.64194306e-01 9.56732569e-02 2.82935332e-01 1.62303216e-02
 6.95547596e-01 4.436348

### Задание 5
Написать функцию для кодирование массива (Run-length encoding). Все подряд повторения элементов функция сжимает в один элемент и считает количество повторений. Функция возвращает кортеж из двух векторов одинаковой длины. Первый содержит элементы, а второй — сколько раз их нужно повторить.

Пример: encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])) = (np.array[1, 2, 3, 1, 5, 2, 3]), np.array[1, 2, 2, 2, 2, 1, 2])

In [145]:
# функция, решающая задачу с помощью NumPy
def np_encode(a):
    if len(a) == 0:
        return np.array([]), np.array([])
    val, lenn = [a[0]], [1]
    for i in range(1, len(a)):
      if a[i] == a[i - 1]:
        lenn[-1] += 1
      else:
        val.append(a[i])
        lenn.append(1)
    return (np.array(val), np.array(lenn))

In [151]:
from itertools import groupby
X = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])
%time x, num = np_encode(X)
print(x, num)
print(np_encode(X))

CPU times: user 39 µs, sys: 4 µs, total: 43 µs
Wall time: 47 µs
[1 2 3 1 5 2 3] [1 2 2 2 2 1 2]
(array([1, 2, 3, 1, 5, 2, 3]), array([1, 2, 2, 2, 2, 1, 2]))


### Задание 6

Пусть задан некоторый одномерный массив $X$. Надо построить новый массив, где все элементы с нечетными индексами требуется заменить на число $a$ (если оно не указано, то на 1). Все элементы с четными индексами нужно возвести в куб. Затем записать элементы в обратном порядке относительно их позиций. Массив $X$ при этом должен остаться *без изменений*. В конце требуется слить массив X с преобразованным X и вывести в обратном порядке.  

Пример:  
X = [100, 200, 300, 400, 500] -> [100, a, 300, a, 500] -> [500^3, a, 300^3, a, 100^3] -> склеиваем -> [100, 200, 300, 400, 500, 500^3, a, 300^3, a, 100^3]

In [199]:
# функция, решающая задачу с помощью NumPy
from copy import copy

def np_transformation(X, a=1):
    """
    param X: array
    """
    dublicate = X.copy()
    dublicate[1::2] = a
    dublicate[::2] **= 3
    dublicate = dublicate[::-1]
    return np.concatenate((X, dublicate))

In [206]:
X = np.array([i for i in range(1, 10, 2)])
# функция должна работать ~ в 20 раз быстрее, чем без Numpy
%time S2 = np_transformation(X, 5)

CPU times: user 76 µs, sys: 0 ns, total: 76 µs
Wall time: 80.3 µs
